### ISSUE TITLE
You could have only one dependency: Mojolicious

### ISSUE THREAD

**Issue by kberov** [kuerbis/App-YTDL#1]
Hi @kuerbis ,
I like the idea of this distribution, but you could implement it with only one of your all dependencies which you listed in the Makefile.PL. This is Mojolicious. It provides all the functionality that you need and you already depend on it. later today (after 20:00 PM CET) I could give more hints if you are interested.

**Comment by kberov** [comment]
Here is one: Use Mojo::UserAgent instead of LWP it is still part of Mojolicious as Mojo::DOM is and even you could implement asynchronous downloads in only one process without forking.

**Comment by kberov** [comment]
Some other hints:

* Encode is already used by Mojolicious;
* File::Which could be implemented with the following piece of code ([steel it from Ado](https://github.com/kberov/Ado/blob/master/lib/Ado/Command/generate/apache2htaccess.pm#L11));
* JSON can be replaced with Mojo::JSON;
* Encode, File::Basename, Getopt::Long, Pod::Usage,Time::HiRes,Exporter,File::Spec are core modules, and may be others, and are already used in Mojolicious
* etc...

**Comment by kberov** [comment]
The whole app can be implemented as a [Mojolicious::Command](https://metacpan.org/pod/Mojolicious::Command). there are even examples on [CPAN](https://metacpan.org/search?q=Mojolicious%3A%3ACommand&size=50). This way it can be used with other applications like [Ado](https://metacpan.org/pod/Ado) for example :) ...

**Comment by kuerbis** [comment]
I will think about it.  Thanks for offering help.

**Comment by kuerbis** [comment]
I've created a new GitHub repo (TEST-App-YTDL) were I use Mojo::UserAgent.
There is an issue with the code from TEST-App-YTDL: when downloading a video now and again I get a 302 response.
And when I get a 302 response, sometimes the download-retry works and sometime the retries return 403 responses.
When I use the original repo (with LWP::UserAgent) all works fine.

**Comment by kuerbis** [comment]
I keep this app as it is and consider using Mojolicious::Command if I write a new app.
